### ISSUE TITLE
Windows Machine running 1.18.2 Fabric Server critical error

### ISSUE THREAD

**Issue by JsephGriff** [timvisee/lazymc#30]
Hi! I have been having a non-stop issue with LazyMC controlling my 1.18.2 fabric server jar. The server refuses to start with this error, which only occurs upon using LazyMC. If I use any other script to start the server including running the Jar, the server will launch fine without error. My java 17 paths are all properly used, and even by typing the default script thru the lazymc.toml config, such as:  command = "java -Xmx1G -Xms1G -jar fabric-server.jar --nogui" 
the error still persists.

INFO  lazymc > Rewritten server.properties file with updated values
 INFO  lazymc > Proxying public ~~~~~~~:25565 to server ~~~~~~~~:25566
 INFO  lazymc > Starting server...
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:114)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:103)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:101)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:94)
        at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:183)
        at java.base/java.io.File.toPath(File.java:2387)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:257)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:541)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:767)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:675)
Caused by: java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\C:\Users\Name\Documents\Server
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsFileSystem.<init>(WindowsFileSystem.java:51)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.<init>(WindowsFileSystemProvider.java:54)
        at java.base/sun.nio.fs.DefaultFileSystemProvider.<clinit>(DefaultFileSystemProvider.java:34)
        ... 18 more
 WARN  lazymc > Server process stopped with error code (exit code: 1)

**Comment by JsephGriff** [comment]
So sorry, I did not see a previously closed issue with the same exact error. For future reference, manually setting the directory in the config saved everything. I nearly did a full on windows re-install because I thought my java path's were all busted, based on the error thrown from this bug. SHEESH.

**Comment by timvisee** [comment]
Great to see you were able to fix it!

Sadly, I don't think there's an easy way to fix this automatically.
