### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by 253488655422** [timvisee/lazymc#62]
I don't care if someone else had this issue I've been looking over the issues and it was never explained how to fix this:
I tried replacing the server start commands multiple times and reloaded the config. (Also I changed the server version to
1.20.1 and protocol to 763 and it still didn't change it still thinks the client needs to be 1.19.3

Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:114)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:103)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:101)
        at java.base/java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:94)
        at java.base/java.nio.file.FileSystems.getDefault(FileSystems.java:183)
        at java.base/java.io.File.toPath(File.java:2387)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:257)
        at java.base/sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:552)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:778)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:686)
Caused by: java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\E:\Foxia
        at java.base/sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsFileSystem.<init>(WindowsFileSystem.java:51)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.<init>(WindowsFileSystemProvider.java:54)
        at java.base/sun.nio.fs.DefaultFileSystemProvider.<clinit>(DefaultFileSystemProvider.java:34)
        ... 18 more

**Comment by 253488655422** [comment]
I updated to Java 21 and I got less errors but now I have a different error even though I'm running Purpur for 1.20.1 I got:
Error: Could not find or load main class io.papermc.paperclip.Main
Caused by: java.lang.ClassNotFoundException: io.papermc.paperclip.Main

**Comment by 253488655422** [comment]
I switched back to to spigot and I got the same error: Error: Could not find or load main class org.bukkit.craftbukkit.bootstrap.Main
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.bootstrap.Main

Since purpur is a fork of paper and spigot is a fork of bukkit I think that's why it's called that in the error.

**Comment by 253488655422** [comment]
![image](https://github.com/timvisee/lazymc/assets/35547883/3c42b156-9376-4ef3-9bf3-63859cb4ef2b)

**Comment by 253488655422** [comment]
[lazymc.txt](https://github.com/timvisee/lazymc/files/13851549/lazymc.txt)

**Comment by 253488655422** [comment]
![Screenshot (839)](https://github.com/timvisee/lazymc/assets/35547883/2310025b-5f4d-4b03-929f-a7b3b5bfdb66)

**Comment by 253488655422** [comment]
My friend help test it on his end he found out that you have to set the sever path/directory on line 30 to have double slashes \\ 
for windows.
(C:\\folder\\server)

❌This won't work:
![wontwork](https://github.com/timvisee/lazymc/assets/35547883/eee4a722-6b34-461d-9d93-9629a9a1c831)

✔But this will work:
![willwork](https://github.com/timvisee/lazymc/assets/35547883/eb20112a-6550-45b5-b98b-b79ba7c575eb)

Please I'm begging you please add this to the documentation page.
